/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "MyWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "distributionLinkable": {
      "cloudfrontDomain": string
      "type": "sst.sst.Linkable"
    }
    "songandtaestudio-photos-dev": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}
