/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "MyWeb": {
      "type": "sst.aws.Nextjs"
    }
    "bucketNameLinkable": {
      "name": string
      "type": "sst.sst.Linkable"
    }
    "contact-us-email": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "distributionLinkable": {
      "cloudfrontDomain": string
      "type": "sst.sst.Linkable"
    }
    "sesSenderLinkable": {
      "email": string
      "type": "sst.sst.Linkable"
    }
    "songandtaestudio-photos-dev": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}